apiVersion: v1
kind: ConfigMap
metadata:
  name: pace-flow-creds
  namespace: flow
data:
  GOOGLE_CLOUD_PROJECT: dome-platform-staging
  CAMUNDA_REST_BASE_URL: https://flow.usepace.delivery/engine-rest
  DOME_LITE_REST_BASE_URL: https://dome-lite-backend.usepace.delivery
  GOOGLE_APPLICATION_CREDENTIALS: /etc/secrets/pace-flow-key.json
  CAMUNDA_USERNAME: ADMIN
  CAMUNDA_PASSWORD: ADMIN
  DOME_LITE_USERNAME: ADMIN
  DOME_LITE_PASSWORD: ADMIN